#!/bin/bash

# First we have to find the formal C dependancy files
# The hard part is we then have to find out the informal dependacies
# and I'm not sure how to do that, but the plugin developer needs to specify it somewhere

DEPS=(smoothlang/anc2020/numeral.c smoothlang/anc2020/iochar.c smoothlang/anc2020/iocons.c -lpthread)

# Shouldn't be too to generate this one though
OUTNAME="smoothlang_anc2020_test"

# Holds the bulk of the runtime
CORE="smoothlang/anc2020/smooth_core.c"

OUT1="-o $OUTNAME"
OUT2="-S"
OUT3="-E"

# This should be "-o $OUTNAME" unless we find a "-S" or "-E" on the commandline.
OUT=$OUT1

# Todo: expose an option for this
CCC=clang

$CCC $OUT -I. -xc ${@:2} $CORE ${DEPS[@]} -
